### ISSUE TITLE
Error: [API Error] Can't convert to integer: "-22450"

### ISSUE THREAD

**Issue by philippkueng** [actualbudget/node-api#4]
Hi James,

My importing script which has been working fine for the last year and a half has stopped working after upgrading Actual today due to an issue parsing the amount of a transaction.

The error (for a payment transaction):

```
Error: [API Error] Can't convert to integer: "-22450"
    at /.../node_modules/@actual-app/api/connection.js:26:13
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

And this test in javascript worked just fine

```
parseInt("-22450"); // => -22450
```

Which begs the question, did you introduce another way one has to define a payment transaction if so could you point me in the right direction please? I checked on https://actualbudget.com/docs/developers/API/#importtransactions but it either wasn't written there or hasn't jumped out a me enough.

The Version of Actual I got running is 0.1.130, sadly I cannot recall what the previous version was which I had running but I haven't been upgrading since November 2020.

And using `"@actual-app/api": "1.1.2"` as the dependency.

Have a nice day,
Regards, Philipp

**Comment by jlongster** [comment]
The issue is that you are passing a string to `amount`, but you must pass an integer. Try doing `amount: parseInt(amount)` to parse it yourself before passing it through.
